name: flutter_common
description: Flutter Common package.
version: 0.3.7
author: patrick<xcpxcp198608@gmail.com>
homepage: https://github.com/wiatec
repository: https://github.com/wiatec/flutter_common

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  dio: ^2.1.10
  encrypt: ^3.3.1
  crypto: ^2.1.3
  screen: ^0.0.5
  provide: ^1.0.2
  path: ^1.6.4
  share: ^0.6.2+1
  path_provider: ^1.3.0
  device_info: ^0.4.0+2
  package_info: ^0.4.0+6
  connectivity: ^0.4.4
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.3+4
  url_launcher: ^5.1.4
  rxdart: ^0.22.2
  local_auth: ^0.6.0
  logger: ^0.7.0+2
  sqflite: ^1.1.6+5

  # widgets
  cached_network_image: ^1.1.1
  flutter_slidable: ^0.5.3
  webview_flutter: ^0.3.14+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true


# sudo flutter packages pub publish --dry-run
# sudo flutter packages pub publish