name: flutter_common
description: Flutter Common package.
version: 0.3.1
author: patrick<xcpxcp198608@gmail.com>
homepage: https://github.com/wiatec
repository: https://github.com/wiatec/flutter_common

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  dio: ^2.1.10
  encrypt: ^3.1.0
  crypto: ^2.0.6
  screen: ^0.0.5
  provide: ^1.0.2
  device_info: ^0.4.0+1
  package_info: ^0.4.0+4
  json_annotation: ^2.4.0
  shared_preferences: ^0.5.2+1
  url_launcher: ^5.0.2
  rxdart: ^0.22.0
  local_auth: ^0.5.2+4
  logger: ^0.7.0+2

  # widgets
  cached_network_image: ^1.0.0
  flutter_webview_plugin: ^0.3.5
  flutter_slidable: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.0.0

flutter:
  uses-material-design: true


# sudo flutter packages pub publish --dry-run
# sudo flutter packages pub publish